name: Actualizador Automático

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías de Scraping
        run: pip install requests beautifulsoup4

      - name: Ejecutar bot de Cuevana
        run: python Update_list.py

      - name: Guardar cambios en la lista
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Bot: Películas de Cuevana actualizadas" || exit 0
          git push
